export const imageAssets: Record<string, string> = {
    "/tech-coding.jpg": "/tech-coding.jpg",
    "/science-engineering.png": "/science-engineering.png",
    "/business-finance.jpg": "/business-finance.jpg",
    "/health-fitness.png": "/health-fitness.png",
    "/arts-creativity.png": "/arts-creativity.png",
    "/language-communication.png": "/language-communication.png",
    "/personal-development.png": "/personal-development.png",
    "/history-culture.png": "/history-culture.png",
    "/math-logic.webp": "/math-logic.webp",
    "/education-teaching.webp": "/education-teaching.webp",
    "/lifestyle-hobbies.webp": "/lifestyle-hobbies.webp",
    "/marketing-sales.webp": "/marketing-sales.webp",
    "/design-ux.jpg": "/design-ux.jpg",
    "/law-government.jpeg": "/law-government.jpeg",
    "/environment-sustainability.jpg": "/environment-sustainability.jpg",
    "/photography-videography.jpg": "/photography-videography.jpg",
    "/music-audio.jpg": "/music-audio.jpg",
    "/food-cooking.jpg": "/food-cooking.jpg",
    "/travel-adventure.jpg": "/travel-adventure.jpg",
    "/sports-recreation.jpg": "/sports-recreation.jpg",
    "/parenting-family.jpg": "/parenting-family.jpg",
    "/psychology-mental-health.jpg": "/psychology-mental-health.jpg",
    "/writing-literature.webp": "/writing-literature.webp",
    "/religion-spirituality.webp": "/religion-spirituality.webp",
    "/automotive-vehicles.jpg": "/automotive-vehicles.jpg",
    "/real-estate-property.webp": "/real-estate-property.webp",
    "/science-fiction-fantasy.webp": "/science-fiction-fantasy.webp",
    "/gaming-esports.webp": "/gaming-esports.webp",
    "/crafts-diy.jpg": "/crafts-diy.jpg",
    "/technology-gadgets.png": "/technology-gadgets.png",
    "/investing-trading.jpg": "/investing-trading.jpg",
    "/human-resources-recruiting.jpeg": "/human-resources-recruiting.jpeg",
    "/economics-policy.webp": "/economics-policy.webp",
    "/public-speaking-presentation.jpg": "/public-speaking-presentation.jpg",
    "/data-science-analytics.jpg": "/data-science-analytics.jpg",
    "/artificial-intelligence-machine-learning.jpg": "/artificial-intelligence-machine-learning.jpg",
    "/cybersecurity.jpg": "/cybersecurity.jpg",
    "/blockchain-cryptocurrency.jpg": "/blockchain-cryptocurrency.jpg",
    "/graphic-design.jpg": "/graphic-design.jpg",
    "/animation-motion-graphics.jpg": "/animation-motion-graphics.jpg",
    "/interior-design.jpg": "/interior-design.jpg",
    "/fashion-beauty.jpg": "/fashion-beauty.jpg",
    "/entrepreneurship.jpg": "/entrepreneurship.jpg",
    "/customer-service-support.jpg": "/customer-service-support.jpg",
    "/project-management.webp": "/project-management.webp",
    "/language-learning.png": "/language-learning.png",
    "/social-media.webp": "/social-media.webp",
    "/career-development.jpg": "/career-development.jpg",
    "/sustainability-green-tech.png": "/sustainability-green-tech.png",
};

export const VideoCategory = [
    { label: "Tech & Coding", value: "Tech & Coding" },
    { label: "Business & Finance", value: "Business & Finance" },
    { label: "Health & Fitness", value: "Health & Fitness" },
    { label: "Science & Engineering", value: "Science & Engineering" },
    { label: "Arts & Creativity", value: "Arts & Creativity" },
    { label: "Language & Communication", value: "Language & Communication" },
    { label: "Personal Development", value: "Personal Development" },
    { label: "History & Culture", value: "History & Culture" },
    { label: "Math & Logic", value: "Math & Logic" },
    { label: "Education & Teaching", value: "Education & Teaching" },
    { label: "Lifestyle & Hobbies", value: "Lifestyle & Hobbies" },
    { label: "Marketing & Sales", value: "Marketing & Sales" },
    { label: "Design & UX", value: "Design & UX" },
    { label: "Law & Government", value: "Law & Government" },
    { label: "Environment & Sustainability", value: "Environment & Sustainability" },
    { label: "Photography & Videography", value: "Photography & Videography" },
    { label: "Music & Audio", value: "Music & Audio" },
    { label: "Food & Cooking", value: "Food & Cooking" },
    { label: "Travel & Adventure", value: "Travel & Adventure" },
    { label: "Sports & Recreation", value: "Sports & Recreation" },
    { label: "Parenting & Family", value: "Parenting & Family" },
    { label: "Psychology & Mental Health", value: "Psychology & Mental Health" },
    { label: "Writing & Literature", value: "Writing & Literature" },
    { label: "Religion & Spirituality", value: "Religion & Spirituality" },
    { label: "Automotive & Vehicles", value: "Automotive & Vehicles" },
    { label: "Real Estate & Property", value: "Real Estate & Property" },
    { label: "Science Fiction & Fantasy", value: "Science Fiction & Fantasy" },
    { label: "Gaming & Esports", value: "Gaming & Esports" },
    { label: "Crafts & DIY", value: "Crafts & DIY" },
    { label: "Technology & Gadgets", value: "Technology & Gadgets" },
    { label: "Investing & Trading", value: "Investing & Trading" },
    { label: "Human Resources & Recruiting", value: "Human Resources & Recruiting" },
    { label: "Economics & Policy", value: "Economics & Policy" },
    { label: "Public Speaking & Presentation", value: "Public Speaking & Presentation" },
    { label: "Data Science & Analytics", value: "Data Science & Analytics" },
    { label: "Artificial Intelligence & Machine Learning", value: "Artificial Intelligence & Machine Learning" },
    { label: "Cybersecurity", value: "Cybersecurity" },
    { label: "Blockchain & Cryptocurrency", value: "Blockchain & Cryptocurrency" },
    { label: "Graphic Design", value: "Graphic Design" },
    { label: "Animation & Motion Graphics", value: "Animation & Motion Graphics" },
    { label: "Interior Design", value: "Interior Design" },
    { label: "Fashion & Beauty", value: "Fashion & Beauty" },
    { label: "Entrepreneurship", value: "Entrepreneurship" },
    { label: "Customer Service & Support", value: "Customer Service & Support" },
    { label: "Project Management", value: "Project Management" },
    { label: "Language Learning", value: "Language Learning" },
    { label: "Social Media", value: "Social Media" },
    { label: "Career Development", value: "Career Development" },
    { label: "Sustainability & Green Tech", value: "Sustainability & Green Tech" },
] as const;

// Extract only the string literal values
export const VideoCategoryValues = VideoCategory.map(c => c.value) as [
    string,
    ...string[]
];

// Strong type for category
export type VideoCategoryType = typeof VideoCategoryValues[number];

export const VisibilityOptions = ["public", "private"] as const;

export const levelOptions = ["beginner", "advance"] as const;
