
auth.token=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

defaults.org=chefu
defaults.project=chefu-academy

defaults.url=https://sentry.io/
