export type Element = {
    atomicNumber: number;
    symbol: string;
    name: string;
    group: string;
};

export const ELEMENTS: Element[] = [
    { atomicNumber: 1, symbol: "H", name: "Hydrogen", group: "nonmetal" },
    { atomicNumber: 2, symbol: "He", name: "Helium", group: "noble gas" },
    { atomicNumber: 3, symbol: "Li", name: "Lithium", group: "alkali metal" },
    { atomicNumber: 4, symbol: "Be", name: "Beryllium", group: "alkaline earth metal" },
    { atomicNumber: 5, symbol: "B", name: "Boron", group: "metalloid" },
    { atomicNumber: 6, symbol: "C", name: "Carbon", group: "nonmetal" },
    { atomicNumber: 7, symbol: "N", name: "Nitrogen", group: "nonmetal" },
    { atomicNumber: 8, symbol: "O", name: "Oxygen", group: "nonmetal" },
    { atomicNumber: 9, symbol: "F", name: "Fluorine", group: "halogen" },
    { atomicNumber: 10, symbol: "Ne", name: "Neon", group: "noble gas" },
    { atomicNumber: 11, symbol: "Na", name: "Sodium", group: "alkali metal" },
    { atomicNumber: 12, symbol: "Mg", name: "Magnesium", group: "alkaline earth metal" },
    { atomicNumber: 13, symbol: "Al", name: "Aluminium", group: "post-transition metal" },
    { atomicNumber: 14, symbol: "Si", name: "Silicon", group: "metalloid" },
    { atomicNumber: 15, symbol: "P", name: "Phosphorus", group: "nonmetal" },
    { atomicNumber: 16, symbol: "S", name: "Sulfur", group: "nonmetal" },
    { atomicNumber: 17, symbol: "Cl", name: "Chlorine", group: "halogen" },
    { atomicNumber: 18, symbol: "Ar", name: "Argon", group: "noble gas" },
    { atomicNumber: 19, symbol: "K", name: "Potassium", group: "alkali metal" },
    { atomicNumber: 20, symbol: "Ca", name: "Calcium", group: "alkaline earth metal" },
    { atomicNumber: 21, symbol: "Sc", name: "Scandium", group: "transition metal" },
    { atomicNumber: 22, symbol: "Ti", name: "Titanium", group: "transition metal" },
    { atomicNumber: 23, symbol: "V", name: "Vanadium", group: "transition metal" },
    { atomicNumber: 24, symbol: "Cr", name: "Chromium", group: "transition metal" },
    { atomicNumber: 25, symbol: "Mn", name: "Manganese", group: "transition metal" },
    { atomicNumber: 26, symbol: "Fe", name: "Iron", group: "transition metal" },
    { atomicNumber: 27, symbol: "Co", name: "Cobalt", group: "transition metal" },
    { atomicNumber: 28, symbol: "Ni", name: "Nickel", group: "transition metal" },
    { atomicNumber: 29, symbol: "Cu", name: "Copper", group: "transition metal" },
    { atomicNumber: 30, symbol: "Zn", name: "Zinc", group: "transition metal" },
    { atomicNumber: 31, symbol: "Ga", name: "Gallium", group: "post-transition metal" },
    { atomicNumber: 32, symbol: "Ge", name: "Germanium", group: "metalloid" },
    { atomicNumber: 33, symbol: "As", name: "Arsenic", group: "metalloid" },
    { atomicNumber: 34, symbol: "Se", name: "Selenium", group: "nonmetal" },
    { atomicNumber: 35, symbol: "Br", name: "Bromine", group: "halogen" },
    { atomicNumber: 36, symbol: "Kr", name: "Krypton", group: "noble gas" },
    { atomicNumber: 37, symbol: "Rb", name: "Rubidium", group: "alkali metal" },
    { atomicNumber: 38, symbol: "Sr", name: "Strontium", group: "alkaline earth metal" },
    { atomicNumber: 39, symbol: "Y", name: "Yttrium", group: "transition metal" },
    { atomicNumber: 40, symbol: "Zr", name: "Zirconium", group: "transition metal" },
    { atomicNumber: 41, symbol: "Nb", name: "Niobium", group: "transition metal" },
    { atomicNumber: 42, symbol: "Mo", name: "Molybdenum", group: "transition metal" },
    { atomicNumber: 43, symbol: "Tc", name: "Technetium", group: "transition metal" },
    { atomicNumber: 44, symbol: "Ru", name: "Ruthenium", group: "transition metal" },
    { atomicNumber: 45, symbol: "Rh", name: "Rhodium", group: "transition metal" },
    { atomicNumber: 46, symbol: "Pd", name: "Palladium", group: "transition metal" },
    { atomicNumber: 47, symbol: "Ag", name: "Silver", group: "transition metal" },
    { atomicNumber: 48, symbol: "Cd", name: "Cadmium", group: "transition metal" },
    { atomicNumber: 49, symbol: "In", name: "Indium", group: "post-transition metal" },
    { atomicNumber: 50, symbol: "Sn", name: "Tin", group: "post-transition metal" },
    { atomicNumber: 51, symbol: "Sb", name: "Antimony", group: "metalloid" },
    { atomicNumber: 52, symbol: "Te", name: "Tellurium", group: "metalloid" },
    { atomicNumber: 53, symbol: "I", name: "Iodine", group: "halogen" },
    { atomicNumber: 54, symbol: "Xe", name: "Xenon", group: "noble gas" },
    { atomicNumber: 55, symbol: "Cs", name: "Cesium", group: "alkali metal" },
    { atomicNumber: 56, symbol: "Ba", name: "Barium", group: "alkaline earth metal" },
    { atomicNumber: 57, symbol: "La", name: "Lanthanum", group: "lanthanide" },
    { atomicNumber: 58, symbol: "Ce", name: "Cerium", group: "lanthanide" },
    { atomicNumber: 59, symbol: "Pr", name: "Praseodymium", group: "lanthanide" },
    { atomicNumber: 60, symbol: "Nd", name: "Neodymium", group: "lanthanide" },
    { atomicNumber: 61, symbol: "Pm", name: "Promethium", group: "lanthanide" },
    { atomicNumber: 62, symbol: "Sm", name: "Samarium", group: "lanthanide" },
    { atomicNumber: 63, symbol: "Eu", name: "Europium", group: "lanthanide" },
    { atomicNumber: 64, symbol: "Gd", name: "Gadolinium", group: "lanthanide" },
    { atomicNumber: 65, symbol: "Tb", name: "Terbium", group: "lanthanide" },
    { atomicNumber: 66, symbol: "Dy", name: "Dysprosium", group: "lanthanide" },
    { atomicNumber: 67, symbol: "Ho", name: "Holmium", group: "lanthanide" },
    { atomicNumber: 68, symbol: "Er", name: "Erbium", group: "lanthanide" },
    { atomicNumber: 69, symbol: "Tm", name: "Thulium", group: "lanthanide" },
    { atomicNumber: 70, symbol: "Yb", name: "Ytterbium", group: "lanthanide" },
    { atomicNumber: 71, symbol: "Lu", name: "Lutetium", group: "lanthanide" },
    { atomicNumber: 72, symbol: "Hf", name: "Hafnium", group: "transition metal" },
    { atomicNumber: 73, symbol: "Ta", name: "Tantalum", group: "transition metal" },
    { atomicNumber: 74, symbol: "W", name: "Tungsten", group: "transition metal" },
    { atomicNumber: 75, symbol: "Re", name: "Rhenium", group: "transition metal" },
    { atomicNumber: 76, symbol: "Os", name: "Osmium", group: "transition metal" },
    { atomicNumber: 77, symbol: "Ir", name: "Iridium", group: "transition metal" },
    { atomicNumber: 78, symbol: "Pt", name: "Platinum", group: "transition metal" },
    { atomicNumber: 79, symbol: "Au", name: "Gold", group: "transition metal" },
    { atomicNumber: 80, symbol: "Hg", name: "Mercury", group: "transition metal" },
    { atomicNumber: 81, symbol: "Tl", name: "Thallium", group: "post-transition metal" },
    { atomicNumber: 82, symbol: "Pb", name: "Lead", group: "post-transition metal" },
    { atomicNumber: 83, symbol: "Bi", name: "Bismuth", group: "post-transition metal" },
    { atomicNumber: 84, symbol: "Po", name: "Polonium", group: "post-transition metal" },
    { atomicNumber: 85, symbol: "At", name: "Astatine", group: "halogen" },
    { atomicNumber: 86, symbol: "Rn", name: "Radon", group: "noble gas" },
    { atomicNumber: 87, symbol: "Fr", name: "Francium", group: "alkali metal" },
    { atomicNumber: 88, symbol: "Ra", name: "Radium", group: "alkaline earth metal" },
    { atomicNumber: 89, symbol: "Ac", name: "Actinium", group: "actinide" },
    { atomicNumber: 90, symbol: "Th", name: "Thorium", group: "actinide" },
    { atomicNumber: 91, symbol: "Pa", name: "Protactinium", group: "actinide" },
    { atomicNumber: 92, symbol: "U", name: "Uranium", group: "actinide" },
    { atomicNumber: 93, symbol: "Np", name: "Neptunium", group: "actinide" },
    { atomicNumber: 94, symbol: "Pu", name: "Plutonium", group: "actinide" },
    { atomicNumber: 95, symbol: "Am", name: "Americium", group: "actinide" },
    { atomicNumber: 96, symbol: "Cm", name: "Curium", group: "actinide" },
    { atomicNumber: 97, symbol: "Bk", name: "Berkelium", group: "actinide" },
    { atomicNumber: 98, symbol: "Cf", name: "Californium", group: "actinide" },
    { atomicNumber: 99, symbol: "Es", name: "Einsteinium", group: "actinide" },
    { atomicNumber: 100, symbol: "Fm", name: "Fermium", group: "actinide" },
    { atomicNumber: 101, symbol: "Md", name: "Mendelevium", group: "actinide" },
    { atomicNumber: 102, symbol: "No", name: "Nobelium", group: "actinide" },
    { atomicNumber: 103, symbol: "Lr", name: "Lawrencium", group: "actinide" },
    { atomicNumber: 104, symbol: "Rf", name: "Rutherfordium", group: "transition metal" },
    { atomicNumber: 105, symbol: "Db", name: "Dubnium", group: "transition metal" },
    { atomicNumber: 106, symbol: "Sg", name: "Seaborgium", group: "transition metal" },
    { atomicNumber: 107, symbol: "Bh", name: "Bohrium", group: "transition metal" },
    { atomicNumber: 108, symbol: "Hs", name: "Hassium", group: "transition metal" },
    { atomicNumber: 109, symbol: "Mt", name: "Meitnerium", group: "unknown" },
    { atomicNumber: 110, symbol: "Ds", name: "Darmstadtium", group: "unknown" },
    { atomicNumber: 111, symbol: "Rg", name: "Roentgenium", group: "unknown" },
    { atomicNumber: 112, symbol: "Cn", name: "Copernicium", group: "transition metal" },
    { atomicNumber: 113, symbol: "Nh", name: "Nihonium", group: "post-transition metal" },
    { atomicNumber: 114, symbol: "Fl", name: "Flerovium", group: "post-transition metal" },
    { atomicNumber: 115, symbol: "Mc", name: "Moscovium", group: "post-transition metal" },
    { atomicNumber: 116, symbol: "Lv", name: "Livermorium", group: "post-transition metal" },
    { atomicNumber: 117, symbol: "Ts", name: "Tennessine", group: "halogen" },
    { atomicNumber: 118, symbol: "Og", name: "Oganesson", group: "noble gas" },
];
