import { StyleSheet } from "react-native";
import { Colors } from "../constant/Colors";
import { scale, verticalScale, moderateScale } from "react-native-size-matters";

export const styles = StyleSheet.create({
    modalContainer: {
        flex: 1,
        backgroundColor: "rgba(0,0,0,0.6)",
        justifyContent: "center",
        alignItems: "center",
    },
    modalContent: {
        backgroundColor: "#121212",
        padding: moderateScale(30),
        borderRadius: moderateScale(16),
        alignItems: "center",
        width: scale(300),
    },
    modalTitle: {
        fontSize: scale(20),
        fontFamily: "outfit-bold",
        color: Colors.GREEN,
        marginTop: verticalScale(15),
    },
    modalSubtext: {
        fontSize: scale(14),
        color: "#ccc",
        textAlign: "center",
        marginTop: verticalScale(8),
        fontFamily: "outfit",
    },
    textInput: {
        padding: moderateScale(15),
        backgroundColor: Colors.WHITE,
        width: "100%",
        borderRadius: moderateScale(10),
        marginTop: verticalScale(20),
        color: "green",
        height: verticalScale(90),
        alignItems: "flex-start",
        fontSize: scale(16),
        fontFamily: "outfit-bold",
    },
    buttonRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        width: "100%",
        marginTop: verticalScale(10),
    },
    cancelButton: {
        flex: 1,
        padding: moderateScale(10),
        marginRight: moderateScale(10),
        alignItems: "center",
    },
    cancelText: {
        fontFamily: "outfit-bold",
        color: "red",
        textAlign: "center",
        marginTop: verticalScale(10),
        fontSize: scale(16),
    },
    subscribeButton: {
        flex: 1,
        padding: moderateScale(10),
        borderRadius: moderateScale(10),
        backgroundColor: Colors.GREEN,
        alignItems: "center",
        marginTop: verticalScale(10),
    },
    subscribeText: {
        fontWeight: "bold",
        color: Colors.WHITE,
        fontSize: scale(16),
    },
    title: {
        fontFamily: "outfit",
        fontSize: scale(16),
        color: "#fff",
        marginTop: verticalScale(5),
    },
    subtitle: {
        fontFamily: "outfit",
        fontSize: scale(14),
        color: "#666",
        marginTop: verticalScale(10),
    },
    backIcon: {
        padding: moderateScale(3),
        borderRadius: moderateScale(10),
        backgroundColor: Colors.BG_GRAY,
    },
    container: {
        flexDirection: "row",
        alignItems: "center",
        gap: moderateScale(10),
        paddingHorizontal: moderateScale(30),
        paddingTop: verticalScale(40),
        backgroundColor: Colors.BG_COLOR,
        zIndex: 10,
    },
    header: {
        fontFamily: "outfit-bold",
        fontSize: scale(24),
        color: Colors.PRIMARY,
    },
    topicsContainer: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: moderateScale(10),
        marginTop: verticalScale(6),
    },
    topics: {
        padding: verticalScale(7),
        borderWidth: 0.4,
        borderColor: Colors.WHITE,
        borderRadius: moderateScale(99),
        paddingHorizontal: moderateScale(15),
    },
    selectTopic: {
        fontFamily: "outfit",
        fontSize: scale(17),
        color: "#fff",
    },
});
