import { StyleSheet } from "react-native";
import { Colors } from "../constant/Colors";

export const styles = StyleSheet.create({
  modalContainer: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "#121212",
    padding: 30,
    borderRadius: 16,
    alignItems: "center",
    width: 300,
  },
  modalTitle: {
    fontSize: 20,
    fontFamily: "outfit-bold",
    color: Colors.GREEN,
    marginTop: 15,
  },
  modalSubtext: {
    fontSize: 14,
    color: "#ccc",
    textAlign: "center",
    marginTop: 8,
    fontFamily: "outfit",
  },
  textInput: {
    padding: 15,
    backgroundColor: Colors.WHITE,
    width: "100%",
    borderRadius: 10,
    marginTop: 20,
    color: "green", // Assuming a dark text color for input
    height: 90,
    alignItems: "flex-start",
    fontSize: 16,
    fontFamily: "outfit-bold",
  },
  buttonRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
  },
  cancelButton: {
    flex: 1,
    padding: 10,
    marginRight: 10,
    alignItems: "center",
  },
  cancelText: {
    fontFamily: "outfit-bold",
    color: "red",
    textAlign: "center",
    marginTop: 10,
    fontSize: 16,
  },
  subscribeButton: {
    flex: 1,
    padding: 10,
    borderRadius: 10,
    backgroundColor: Colors.GREEN,
    alignItems: "center",
    marginTop: 10,
  },
  subscribeText: {
    fontWeight: "bold",
    color: Colors.WHITE,
    fontSize: 16,
  },
  title: {
    fontFamily: "outfit",
    fontSize: 16,
    color: "#fff",
    marginTop: 5,
  },
  subtitle: {
    fontFamily: "outfit",
    fontSize: 14,
    color: "#666",
    marginTop: 10,
  },
  backIcon: {
    padding: 3,
    borderRadius: 10,
    backgroundColor: Colors.BG_GRAY,
  },
  container: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 30,
    paddingTop: 40,
    backgroundColor: Colors.BG_COLOR,
    zIndex: 10,
  },
  header: {
    fontFamily: "outfit-bold",
    fontSize: 24,
    color: Colors.PRIMARY,
  },
  topicsContainer: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 6,
  },
  topics: {
    padding: 7,
    borderWidth: 0.4,
    borderColor: Colors.WHITE,
    borderRadius: 99,
    paddingHorizontal: 15,
  },
  selectTopic: { fontFamily: "outfit", fontSize: 17, color: "#fff" },
});
