import { StyleSheet } from "react-native";
import { Colors } from "../constant/Colors";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#0A0F24",
    },
    title: {
        fontSize: 28,
        fontWeight: "bold",
        color: "#fff",
        marginBottom: 10,
        marginTop: 35,
    },
    chatContainer: {
        paddingHorizontal: 12,
        paddingBottom: 10,
        flexGrow: 1,
    },
    messageContainer: {
        maxWidth: "80%",
        borderRadius: 12,
        padding: 10,
        marginVertical: 5,
    },
    userMessage: {
        backgroundColor: "#4B7BE5",
        alignSelf: "flex-end",
        borderBottomRightRadius: 0,
    },
    aiMessage: {
        backgroundColor: "#222844",
        alignSelf: "flex-start",
        borderBottomLeftRadius: 0,
    },
    messageText: {
        fontSize: 16,
        lineHeight: 22,
    },
    userText: {
        color: "#fff",
    },
    aiText: {
        color: "#ddd",
    },
    inputContainer: {
        flexDirection: "row",
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderTopWidth: 1,
        borderTopColor: "#222844",
        marginBottom: 30,
        maxHeight: 80,
    },
    input: {
        flex: 1,
        color: "#fff",
        fontSize: 16,
        paddingHorizontal: 12,
        paddingVertical: 8,
        backgroundColor: "#222844",
        borderRadius: 20,
        maxHeight: 100,
        marginRight: 8,
        marginLeft: 8,
    },
    sendButton: {
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#24C97D",
        paddingHorizontal: 16,
        marginLeft: 8,
        borderRadius: 20,
    },
    sendButtonText: {
        color: "#fff",
        fontWeight: "bold",
        fontSize: 16,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(0,0,0,0.5)",
        justifyContent: "flex-end",
    },
    modalContent: {
        backgroundColor: Colors.GRAY,
        padding: 20,
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        minHeight: 180,
    },
    modalOption: {
        fontSize: 18,
        paddingVertical: 10,
        fontFamily: "outfit",
        marginLeft: 12,
    },
    modalCloseButton: {
        marginTop: 15,
        backgroundColor: "#222844",
        paddingVertical: 12,
        borderRadius: 20,
        alignItems: "center",
    },
    selectedImageContainer: {
        padding: 12,
        backgroundColor: "#e8e8e82a",
        borderTopLeftRadius: 25,
        borderTopRightRadius: 25,
    },
    selectedImage: {
        width: 150,
        height: 100,
        borderRadius: 12,
        objectFit: "cover",
        borderWidth: 2,
        borderColor: "#438222ff",
    },
    attachFileButton: {
        padding: 10,
        backgroundColor: "#222844",
        borderRadius: 25,
    },
    micContainer: {
        marginTop: 5,
        alignItems: "center",
        justifyContent: "space-between",
        flexDirection: "row",
        gap: 8,
    },
    mic: { padding: 10, backgroundColor: "#222844", borderRadius: 25 },
    attachmentButton: {
        backgroundColor: Colors.LIGHT_GREEN,
        borderRadius: 18,
        marginBottom: 10,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    attachmentText: {
        fontSize: 18,
        marginBottom: 15,
        fontFamily: "outfit-bold",
    },
});
