import { StyleSheet } from 'react-native';
import { Colors } from '../constant/Colors';
import { scale, verticalScale, moderateScale } from 'react-native-size-matters';

export const styles = StyleSheet.create({
    container: {
        padding: moderateScale(25),
        backgroundColor: Colors.BG_COLOR,
        flex: 1,
    },
    backButtonContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: moderateScale(10),
    },
    topic: {
        fontFamily: 'outfit-bold',
        fontSize: scale(20),
        color: Colors.PRIMARY,
        marginBottom: verticalScale(10),
    },
    codeExampleText: {
        backgroundColor: Colors.GREEN,
        padding: moderateScale(15),
        borderRadius: moderateScale(10),
        fontFamily: 'outfit',
        fontSize: scale(14),
        color: Colors.WHITE,
        marginTop: verticalScale(10),
    },
    codeContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: moderateScale(15),
    },
    codeLabel: {
        color: '#8BE9FD',
        fontFamily: 'outfit-bold',
        fontSize: scale(13),
        paddingLeft: moderateScale(15),
        paddingTop: verticalScale(10),
    },
    copyButton: {
        paddingHorizontal: moderateScale(12),
        paddingVertical: verticalScale(4),
        marginRight: moderateScale(10),
        backgroundColor: '#23272F',
        borderRadius: moderateScale(6),
        marginTop: verticalScale(10),
    },
    copyButtonText: {
        color: 'green',
        fontFamily: 'outfit-bold',
        fontSize: scale(13),
    },
    codeBlockTopBar: {
        height: verticalScale(30),
        backgroundColor: '#282c34',
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: moderateScale(15),
        gap: moderateScale(10),
    },
    windowCircle: {
        width: scale(12),
        height: scale(12),
        borderRadius: scale(6),
        marginRight: moderateScale(1),
    },
    circleRed: { backgroundColor: '#ff5f56' },
    circleYellow: { backgroundColor: '#ffbd2e' },
    circleGreen: { backgroundColor: '#27c93f' },
    codeBlockContainer: {
        marginTop: verticalScale(20),
        marginBottom: verticalScale(10),
        borderRadius: moderateScale(10),
        overflow: 'hidden',
        backgroundColor: '#1e1e2f',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 6,
        elevation: 8,
        width: '100%',
        maxWidth: '100%',
    },
    advancedCodeBlock: {
        fontFamily: 'monospace',
        fontSize: scale(15),
        color: '#abb2bf',
        padding: moderateScale(15),
        lineHeight: verticalScale(22),
        minWidth: scale(200),
        backgroundColor: 'transparent',
    },
    explainContainer: {
        marginTop: verticalScale(10),
        flexDirection: 'row',
        flexWrap: 'wrap',
    },
    content: {
        fontFamily: 'monospace',
        fontSize: scale(16),
        color: Colors.YELLOW,
        backgroundColor: '#333',
        borderRadius: moderateScale(5),
        paddingHorizontal: moderateScale(4),
        paddingVertical: verticalScale(2),
    },
    exampleText: {
        fontFamily: 'outfit',
        fontSize: scale(16),
        color: Colors.WHITE,
        marginTop: verticalScale(20),
    },
});
