import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    screen: { backgroundColor: "#0b1020" },
    backButton: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        marginTop: 25,
        backgroundColor: "#0b1020",
    },
    title: {
        color: "#fff",
        fontSize: 20,
        fontFamily: "outfit-bold",
    },
    box: {
        backgroundColor: "#0f1724",
        padding: 12,
        borderRadius: 10,
        marginBottom: 12,
    },
    sub: { color: "#9aa4bf", marginBottom: 8 },
    diagram: {
        color: "#9fe59f",
        fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
        marginTop: 6,
    },
    row: {
        flexDirection: "row",
        justifyContent: "space-between",
        gap: 8,
        marginBottom: 12,
    },
    col: { flex: 1, alignItems: "center", marginHorizontal: 4 },
    label: { color: "#c6d0e6", fontSize: 14, marginBottom: 6 },
    big: { color: "#fff", fontSize: 18, fontWeight: "700" },
    controls: { flexDirection: "row", marginTop: 8 },
    btn: {
        backgroundColor: "#222633",
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 6,
        marginHorizontal: 6,
    },
    btnText: { color: "#fff", fontSize: 18 },
    smallBtn: {
        paddingVertical: 8,
        paddingHorizontal: 10,
        borderRadius: 8,
        backgroundColor: "#222633",
    },
    smallBtnText: { color: "#fff" },
    toggle: { alignSelf: "flex-start", marginBottom: 8 },
    activeBtn: { backgroundColor: "#2a6cff" },
    chargeBar: {
        height: 16,
        backgroundColor: "#263041",
        borderRadius: 8,
        marginTop: 8,
        overflow: "hidden",
    },
    chargeFill: { height: "100%", backgroundColor: "#00d184", width: "0%" },
    smallText: { color: "#b7c1da", marginTop: 6 },
    ledPreview: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
        marginTop: 8,
    },
    ledBubble: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: "#ffb86b",
        borderWidth: 1,
        borderColor: "#ff9a2b",
    },
    actionBtn: {
        padding: 10,
        borderRadius: 8,
        backgroundColor: "#222633",
        marginRight: 8,
    },
    actionText: { color: "#fff" },
    smallAction: {
        padding: 8,
        backgroundColor: "#1b2230",
        borderRadius: 8,
        marginRight: 8,
    },
    smallActionText: { color: "#b7c1da" },
    rowControls: {
        flexDirection: "row",
        justifyContent: "space-between",
        gap: 8,
        marginBottom: 12,
    },
    resetBtn: {
        flex: 1,
        padding: 12,
        backgroundColor: "#ff5555",
        borderRadius: 8,
        alignItems: "center",
    },
    clearBtn: {
        flex: 1,
        padding: 12,
        backgroundColor: "#666",
        borderRadius: 8,
        alignItems: "center",
    },
    resetText: { color: "#fff", fontWeight: "700" },
    smallActionTextCenter: { color: "#fff" },
});
