import { Platform, StyleSheet } from "react-native";
import { Colors } from "../constant/Colors";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Colors.BG_COLOR,
        paddingTop: Platform.OS === "android" ? 40 : 60,
        paddingHorizontal: 16,
        paddingBottom: 25,
    },
    backButton: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 20,
    },
    headerTitle: {
        fontSize: 24,
        color: Colors.WHITE,
        marginLeft: 12,
        fontFamily: "outfit-bold",
    },
    content: {
        flex: 1,
        alignItems: "center",
    },
    label: {
        color: Colors.WHITE,
        fontSize: 16,
        marginBottom: 4,
        fontFamily: "outfit-bold",
    },
    input: {
        backgroundColor: Colors.BLACK || "#222",
        color: Colors.WHITE,
        paddingHorizontal: 12,
        paddingVertical: 8,
        fontSize: 16,
        borderRadius: 8,
        marginBottom: 20,
        width: 300,
        fontWeight: "600",
    },
    controlsRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        width: 300,
        marginBottom: 20,
    },
    unitToggle: {
        backgroundColor: Colors.PRIMARY || "#8E44AD",
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 12,
    },
    unitToggleText: {
        color: Colors.WHITE,
        fontWeight: "600",
        fontSize: 16,
    },
    switchContainer: {
        flexDirection: "row",
        alignItems: "center",
    },
    presetsRow: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "center",
        width: 320,
        marginBottom: 16,
        gap: 10,
    },
    presetButton: {
        backgroundColor: Colors.BLACK || "#222",
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: Colors.PRIMARY || "#8E44AD",
    },
    presetText: {
        color: Colors.WHITE,
        fontWeight: "600",
    },
    resetButton: {
        backgroundColor: Colors.PRIMARY || "#8E44AD",
        paddingVertical: 10,
        paddingHorizontal: 32,
        borderRadius: 12,
        marginBottom: 24,
    },
    resetButtonText: {
        color: "white",
        fontWeight: "600",
        fontSize: 16,
        textAlign: "center",
    },
    visualizationBox: {
        marginTop: 12,
        width: 320,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: Colors.PRIMARY || "#8E44AD",
        padding: 16,
        backgroundColor: Colors.BLACK || "#222",
    },
    visualizationText: {
        color: Colors.WHITE,
        fontSize: 16,
        textAlign: "center",
        marginBottom: 6,
    },
    historyTitle: {
        color: Colors.WHITE,
        fontSize: 16,
        fontWeight: "600",
        marginTop: 12,
        marginBottom: 6,
    },
    historyContainer: {
        flexDirection: "row",
        alignItems: "flex-end",
        height: 100,
        gap: 4,
    },
    historyBar: {
        width: 20,
        borderRadius: 4,
        marginHorizontal: 2,
    },
    historyEmpty: {
        color: Colors.GRAY,
        fontStyle: "italic",
    },
});
