import { Colors } from '@/constant/Colors';
import { StyleSheet } from 'react-native';
import { RFValue } from 'react-native-responsive-fontsize';
import { moderateScale, scale, verticalScale } from 'react-native-size-matters';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    loading: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    backButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(5),
        padding: scale(10),
    },
    backText: {
        fontSize: scale(14),
        color: Colors.PRIMARY,
        fontWeight: '600',
    },
    contentContainer: {
        padding: scale(10),
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: verticalScale(10),
        justifyContent: 'space-between',
        padding: scale(10),
    },
    avatar: {
        width: scale(40),
        height: scale(40),
        borderRadius: scale(20),
        marginRight: scale(10),
        padding: scale(10),
    },
    author: {
        fontSize: scale(14),
        color: Colors.PRIMARY,
        fontFamily: 'outfit-bold',
    },
    timestamp: {
        fontSize: RFValue(10),
        color: '#777',
    },
    categoryBox: {
        backgroundColor: Colors.BG_GRAY,
        paddingVertical: verticalScale(4),
        paddingHorizontal: scale(10),
        borderRadius: scale(10),
        right: scale(10),
    },
    category: {
        fontSize: scale(10),
        fontWeight: '500',
        color: Colors.PRIMARY,
    },
    title: {
        fontSize: scale(14),
        marginBottom: verticalScale(8),
        fontFamily: 'outfit-bold',
        paddingHorizontal: scale(10),
    },
    content: {
        fontSize: scale(13),
        lineHeight: verticalScale(22),
        color: Colors.WHITE,
        marginBottom: verticalScale(20),
        paddingHorizontal: scale(10),
    },
    actions: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        marginBottom: verticalScale(20),
        borderTopWidth: 0.2,
        borderColor: Colors.GRAY,
        paddingTop: verticalScale(10),
    },
    actionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(6),
    },
    actionText: {
        fontSize: scale(14),
        color: Colors.PRIMARY,
    },
    commentsHeader: {
        fontSize: scale(14),
        marginBottom: verticalScale(10),
        fontFamily: 'outfit-bold',
    },
    comment: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: scale(10),
        paddingTop: verticalScale(10),
        borderRadius: scale(10),
        paddingHorizontal: scale(10),
    },
    commentAvatar: {
        width: scale(30),
        height: scale(30),
        borderRadius: scale(14),
        borderWidth: 0.8,
        borderColor: Colors.GRAY,
    },
    commentAuthor: {
        fontSize: scale(14),
        marginBottom: verticalScale(2),
        fontFamily: 'outfit-bold',
        color: Colors.PRIMARY,
    },
    commentText: {
        fontSize: scale(14),
        fontFamily: 'outfit',
    },
    noComments: {
        fontSize: scale(14),
        color: '#888',
    },
    center: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    notFound: {
        fontSize: scale(14),
        color: '#888',
    },
    commentInput: {
        padding: verticalScale(7),
        fontSize: scale(14),
        color: Colors.BLACK,
        backgroundColor: Colors.BG_GRAY,
        maxWidth: '65%',
        borderRadius: scale(20),
        flex: 1,
        fontFamily: 'outfit',
        marginLeft: scale(10),
        marginTop: verticalScale(10),
    },
    addButtonContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderTopWidth: 0.5,
        borderColor: Colors.GRAY,
    },
    postButton: {
        backgroundColor: Colors.PRIMARY,
        paddingVertical: verticalScale(8),
        paddingHorizontal: scale(10),
        borderRadius: scale(10),
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(6),
        marginRight: scale(10),
        marginTop: verticalScale(10),
    },
    commentHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(8),
        justifyContent: 'space-between',
    },
    commentTimestamp: {
        fontSize: scale(10),
        color: '#777',
        fontFamily: 'outfit',
    },
    actionsContainer: {
        flexDirection: 'row',
        marginTop: verticalScale(10),
        marginBottom: verticalScale(5),
        alignItems: 'center',
        gap: scale(20),
    },
    menuTrigger: {
        padding: scale(2),
        borderRadius: scale(20),
    },
    editInput: {
        color: Colors.WHITE,
        fontSize: scale(13),
        borderWidth: 0.7,
        borderColor: Colors.GRAY,
        borderRadius: scale(22),
        flex: 1,
        maxWidth: '75%',
        paddingHorizontal: scale(10),
        paddingVertical: verticalScale(3),
        fontFamily: 'outfit',
        textAlignVertical: 'top',
        minHeight: verticalScale(40),
        maxHeight: verticalScale(100),
        backgroundColor: Colors.BG_GRAY,
    },
    editHeader: {
        backgroundColor: Colors.BG_COLOR,
        padding: scale(20),
        borderRadius: scale(10),
    },
    editText: {
        color: Colors.WHITE,
        fontSize: scale(14),
        fontFamily: 'outfit-bold',
    },
    buttonsContainer: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        gap: scale(10),
    },
    modal: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        padding: scale(20),
    },
    menuOption2: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(5),
        backgroundColor: 'rgba(255, 0, 0, 0.1)',
        padding: scale(5),
        borderRadius: scale(5),
    },
    menuOption1: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(5),
        paddingBottom: verticalScale(5),
        borderBottomWidth: 0.3,
        borderColor: Colors.GRAY,
    },
    optionsContainerStyle: {
        backgroundColor: Colors.BG_COLOR,
        borderRadius: scale(8),
        paddingVertical: verticalScale(5),
        borderWidth: 0.4,
        borderColor: Colors.GRAY,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.3)',
    },
    sheetContainer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        padding: scale(8),
        borderTopLeftRadius: scale(22),
        borderTopRightRadius: scale(22),
        maxHeight: '60%',
        shadowColor: '#000',
        shadowOpacity: 0.2,
        shadowRadius: scale(6),
        elevation: 6,
    },
    replyButton: {
        backgroundColor: Colors.PRIMARY,
        padding: moderateScale(10),
        alignItems: 'center',
        marginLeft: scale(10),
        paddingHorizontal: scale(14),
        borderRadius: scale(22),
    },
    replyText: {
        fontSize: RFValue(14),
        fontFamily: 'outfit-bold',
    },
    noReplyText: {
        color: Colors.GRAY,
        marginBottom: verticalScale(5),
        fontFamily: 'outfit-bold',
    },
    reply: {
        color: Colors.GRAY,
        fontSize: scale(11),
        lineHeight: verticalScale(20),
        maxWidth: scale(270),
    },
    fullname: {
        color: Colors.BLACK,
        fontSize: RFValue(10),
        fontFamily: 'outfit-bold',
    },
    fullnameCont: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    containerReply: {
        paddingVertical: verticalScale(10),
        paddingHorizontal: scale(10),
        borderRadius: scale(10),
        marginTop: scale(8),
        backgroundColor: Colors.BG_GRAY,
    },
    X: {
        flexDirection: 'row',
        gap: scale(10),
    },
    Y: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: verticalScale(40),
    },
    Z: {
        color: Colors.PRIMARY,
        fontFamily: 'outfit',
        marginTop: verticalScale(6),
    },
    A: {
        color: Colors.WHITE,
        fontFamily: 'outfit',
        fontSize: RFValue(10),
    },
    delete: {
        padding: verticalScale(6),
        paddingHorizontal: scale(8),
        backgroundColor: Colors.LIGHT_RED,
        borderRadius: scale(50), // replaced '50%' with scaled value
    },
});
