name: Android Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SENTRY_UPLOAD: false
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - run: npm ci

      - run: npm install -g expo-cli

      - run: rm -rf node_modules/.cache/metro # clear metro cache (optional but helpful)

      - name: Bundle JS and assets
        run: |
          mkdir -p android/app/src/main/assets
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file app/index.jsx \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/assets


      - run: chmod +x android/gradlew

      - name: Build Android release APK
        run: cd android && ./gradlew assembleRelease

      - uses: actions/upload-artifact@v4
        with:
          name: chefuacademy-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Sentry Info
        run: npx sentry-cli info
